services:

  app_proxy:
    environment:
      APP_HOST: umbrel-tunnel-store-tunnel_web_1
      APP_PORT: 3006
      PROXY_AUTH_ADD: "true"

  web:
    image: ghcr.io/miniweed/umbrel-tunnel-web:1.0.2@sha256:6a034507d6630203c5bdc96698f97840d52c83b228ab98a5475530a8e176046f
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - DATA_DIR=/data
      - WG_API_HOST=wg
      - PORT=3006

  wg:
    image: ghcr.io/miniweed/umbrel-tunnel-wg:1.0.1@sha256:47e1da82de412997ccad4621fbcd3235500a6d7e4426838613ec1abb9805faf9
    restart: on-failure
    stop_grace_period: 30s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${APP_DATA_DIR}/data:/data
