services:

  app_proxy:
    environment:
      APP_HOST: miniweed-app-store-tunnel_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "true"

  web:
    image: ghcr.io/miniweed/umbrel-tunnel-web:1.0.1@sha256:76c51c283a727e4b0930ba2b2bab02dcb99fd7c1d7fb8c9040a7ce6809201b83
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - DATA_DIR=/data
      - WG_API_HOST=wg

  wg:
    image: ghcr.io/miniweed/umbrel-tunnel-wg:1.0.1@sha256:47e1da82de412997ccad4621fbcd3235500a6d7e4426838613ec1abb9805faf9
    restart: on-failure
    stop_grace_period: 30s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${APP_DATA_DIR}/data:/data
